wandb_version: 1

batch_size:
  desc: null
  value: 512
test_batch_size:
  desc: null
  value: 1000
epochs:
  desc: null
  value: 50
lr:
  desc: null
  value: 1.0e-05
gamma:
  desc: null
  value: 0.01
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 1
save_model:
  desc: null
  value: false
question_path:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
stat_ques_list:
  desc: null
  value:
  - /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
  - /home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json
use_glove:
  desc: null
  value: false
train_question:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
val_question:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json
max_ques_len:
  desc: null
  value: 20
train_annotation:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Annotation_Train_simpsons_vqa.json
val_annotation:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Annotation_Val_simpsons_vqa.json
_wandb:
  desc: null
  value:
    code_path: code/FSDP_mnist.py
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705467203.84983
    t:
      1:
      - 1
      - 5
      - 33
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 33
      - 41
      - 53
      - 55
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 8
      - 9
      13: linux-x86_64
